// FETCH DEVICES
export const FETCH_DEVICES__REQUEST = 'FETCH_DEVICES__REQUEST';
export const FETCH_DEVICES__FAILURE = 'FETCH_DEVICES__FAILURE';
export const FETCH_DEVICES__SUCCESS = 'FETCH_DEVICES__SUCCESS';

// FETCH FORECAST FOR DEVICES
export const FETCH_FORECAST__REQUEST = 'FETCH_FORECAST__REQUEST';
export const FETCH_FORECAST__FAILURE = 'FETCH_FORECAST__FAILURE';
export const FETCH_FORECAST__SUCCESS = 'FETCH_FORECAST__SUCCESS';

// SETTING ZONE RUNTIME DURATION
export const SET_DURATION__REQUEST = 'SET_DURATION__REQUEST';
export const SET_DURATION__FAILURE = 'SET_DURATION__FAILURE';
export const SET_DURATION__SUCCESS = 'SET_DURATION__SUCCESS';
